### ISSUE TITLE
Can you double check my strict/warn conversion of php-loop.pl?

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-nginx#1]
I'm a little weak on fork behavior, and I'm not sure how to test this code, so I'm not entirely confident I've got the variables scoped in the right places ($childpid and $start, specifically).

Direct link: https://github.com/virtualmin/virtualmin-nginx/blob/master/php-loop.pl

**Comment by jcameron** [comment]
Ok, I've made a small fix that should make it work.
