### ISSUE TITLE
Custom SSL certificate

### ISSUE THREAD

**Issue by rohanvakharia** [virtualmin/virtualmin-nginx#12]
I have (multidomain) SSL certificate and I don't want virtualmin to generate the new certificate while creating new virtual domain, instead it should use predefined certificate files.

Is it possible to do that in the existing setup? If no, would like to consider this as feature?

**Comment by iliarostovtsev** [comment]
> I have (multidomain) SSL certificate and I don't want Virtualmin to generate the new certificate while creating new virtual domain, instead it should use predefined certificate files.

There is an option in Virtualmin configuration that will let you share SSL certs and disable automatic certs requests:

![image](https://user-images.githubusercontent.com/4426533/87874306-7cf4fe80-c9d1-11ea-879f-02ad6f7c2ee3.png)
