### ISSUE TITLE
virtualmin-nginx::feature_list_web_redirects failed : Can't use an undefined value as an ARRAY reference at /usr/share/webmin/virtualmin-nginx/virtual_feature.pl line 1550.

### ISSUE THREAD

**Issue by yusuf81** [virtualmin/virtualmin-nginx#16]
Hello Jamie

Yesterday I set let's encrypt and wildcard subdomain (via website option menu) on my wordpress multisite and run smoothly. Suddenly I realized the day after my website options page on all virtual server show this error.

> virtualmin-nginx::feature_list_web_redirects failed : Can't use an undefined value as an ARRAY reference at /usr/share/webmin/virtualmin-nginx/virtual_feature.pl line 1550.

I think the culprit is my nginx config so I try to repair it by delete my wordpress multise virtual server. But the error still show and because this I cannot assign let's encrypt. 

I try to solve this by "re-check configuration" and running manually via shell "/etc/init.d/nginx configtest" but show no error.

When I see last edit on virtual_feature.pl in this github it's show there's update around this lines (1550).
The question is
1. Is it the bug from virtual_feature.pl or my config had error that I didn't know? 
2. Can I revert to  a version before last update and is it safe?
![image](https://user-images.githubusercontent.com/779414/81559627-f365f680-93b9-11ea-88f0-d1dcb08728b5.png)

Thanks Jamie

**Comment by yusuf81** [comment]
and I found the culprit after digging in. In the nginx config, there's include file that contain line 

> if ( $query_string ~ "rest_route" ) { return 403; } 

when I comment it out, the error is gone.  I think that line hitting some of codes that entered recently. I had no time and skill to debugging out, perl is  out of my league.
Thanks

**Comment by jcameron** [comment]
Thanks - this is a bug in Virtualmin's parsing of the Nginx config that can be triggered by unexpected `if` statements. We'll fix it in the next release.
