### ISSUE TITLE
Undefined subroutine &virtual_server::modify_ipkeys

### ISSUE THREAD

**Issue by SnakeO** [virtualmin/virtualmin-nginx#17]
When I run this command:
virtualmin modify-domain --domain OLD --newdomain NEW --shared-ip IPV4 --shared-ip6 IPV6

I get this error:
Updating virtual server arvadavethospital.com ..

Updating users ..
.. done

Removing from email domains list ..
.. done

Adding to email domains list ..
.. done

Changing domain name in mail aliases ..
.. done

Updating aliases for contact address ..
.. done

Error: virtualmin-nginx-ssl::feature_modify failed : Undefined subroutine &virtual_server::modify_ipkeys called at /usr/share/webmin/virtualmin-nginx-ssl/virtual_feature.pl line 384.

**Comment by iliarostovtsev** [comment]
Dupe: https://github.com/virtualmin/virtualmin-gpl/issues/188

Thanks for heads up.
