### ISSUE TITLE
Nginx fails when IPv6 is enabled upon site creation

### ISSUE THREAD

**Issue by iliarostovtsev** [virtualmin/virtualmin-nginx#18]
It seems that Nginx config isn't written correctly when IPv6 feature is enabled.

![image](https://user-images.githubusercontent.com/4426533/87980096-b44fd200-cadb-11ea-8ae6-e02d2b906af7.png)

**Comment by jcameron** [comment]
Can you post the Nginx config line that contains that IP?

**Comment by iliarostovtsev** [comment]
**/debug-debian9-gpl.local.conf** created virtual-server details:

~~~
server {
	server_name debug-debian9-gpl.local www.debug-debian9-gpl.local;
	listen 192.168.122.225;
	listen [fe80::5054:ff:fea5:3e19];
	root /home/debug-debian9-gpl/public_html;
	index index.html index.htm index.php;
	access_log /var/log/virtualmin/debug-debian9-gpl.local_access_log;
	error_log /var/log/virtualmin/debug-debian9-gpl.local_error_log;
	fastcgi_param GATEWAY_INTERFACE CGI/1.1;
	fastcgi_param SERVER_SOFTWARE nginx;
	fastcgi_param QUERY_STRING $query_string;
	fastcgi_param REQUEST_METHOD $request_method;
	fastcgi_param CONTENT_TYPE $content_type;
	fastcgi_param CONTENT_LENGTH $content_length;
	fastcgi_param SCRIPT_FILENAME /home/debug-debian9-gpl/public_html$fastcgi_script_name;
	fastcgi_param SCRIPT_NAME $fastcgi_script_name;
	fastcgi_param REQUEST_URI $request_uri;
	fastcgi_param DOCUMENT_URI $document_uri;
	fastcgi_param DOCUMENT_ROOT /home/debug-debian9-gpl/public_html;
	fastcgi_param SERVER_PROTOCOL $server_protocol;
	fastcgi_param REMOTE_ADDR $remote_addr;
	fastcgi_param REMOTE_PORT $remote_port;
	fastcgi_param SERVER_ADDR $server_addr;
	fastcgi_param SERVER_PORT $server_port;
	fastcgi_param SERVER_NAME $server_name;
	fastcgi_param HTTPS $https;
	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_pass unix:/var/php-nginx/15954247654096.sock/socket;
	}
}

~~~

**Comment by iliarostovtsev** [comment]
I must say IPv6 configuration on Nginx is not straight forward, and confusing. The config is technically correct according to documentation. However, I could only make the current configuration generated by Virtualmin work only if un-commenting directives for _default_server_ for **[::]:80** and the same for **SSL**, example:

![image](https://user-images.githubusercontent.com/4426533/88205709-d8372300-cc55-11ea-983f-2609d13f8d5a.png)

The difference that Nginx is no longer listening on particular IP according to _netstat_ output:

![image](https://user-images.githubusercontent.com/4426533/88205840-04eb3a80-cc56-11ea-878e-46257d6fc798.png)

.. but sites seem to work just fine with the configuration I just described. It's a mystery to me though, why you need default _Listen_ directives to be active?

**Comment by jcameron** [comment]
It's very odd that you'd need to uncomment the global listen.   Is the IP [fe80::5054:ff:fea5:3e19] from the original error message active on your system?

**Comment by iliarostovtsev** [comment]
> Is the IP [fe80::5054:ff:fea5:3e19] from the original error message active on your system?

Yes.

It's worth mentioning, that the issue practically exists on Debian systems, as by default RHEL has defaults on for IPv6.


![image](https://user-images.githubusercontent.com/4426533/88452806-6ab01000-ce6a-11ea-92f8-24cf81aa7865.png)

 .. however, if you comment out IPv6 from default server and the record exists in one of the created servers - then it fails (on CetnOS too):

![image](https://user-images.githubusercontent.com/4426533/88452839-a8149d80-ce6a-11ea-911c-a710663f3903.png)


.. but it's never listening on particular address, like I already mentioned.

![image](https://user-images.githubusercontent.com/4426533/88452869-d98d6900-ce6a-11ea-8ad2-e57ed7ad7893.png)

SSL connections are bind to specific address, while non-SSL not:

![image](https://user-images.githubusercontent.com/4426533/88452896-1f4a3180-ce6b-11ea-88c6-9313db59d74e.png)

~~~
server {
	server_name debug-centos8-pro.local www.debug-centos8-pro.local;
	listen 192.168.122.145;
	root /home/debug-centos8-pro/public_html;
	index index.html index.htm index.php;
	access_log /var/log/virtualmin/debug-centos8-pro.local_access_log;
	error_log /var/log/virtualmin/debug-centos8-pro.local_error_log;
	fastcgi_param GATEWAY_INTERFACE CGI/1.1;
	fastcgi_param SERVER_SOFTWARE nginx;
	fastcgi_param QUERY_STRING $query_string;
	fastcgi_param REQUEST_METHOD $request_method;
	fastcgi_param CONTENT_TYPE $content_type;
	fastcgi_param CONTENT_LENGTH $content_length;
	fastcgi_param SCRIPT_FILENAME /home/debug-centos8-pro/public_html$fastcgi_script_name;
	fastcgi_param SCRIPT_NAME $fastcgi_script_name;
	fastcgi_param REQUEST_URI $request_uri;
	fastcgi_param DOCUMENT_URI $document_uri;
	fastcgi_param DOCUMENT_ROOT /home/debug-centos8-pro/public_html;
	fastcgi_param SERVER_PROTOCOL $server_protocol;
	fastcgi_param REMOTE_ADDR $remote_addr;
	fastcgi_param REMOTE_PORT $remote_port;
	fastcgi_param SERVER_ADDR $server_addr;
	fastcgi_param SERVER_PORT $server_port;
	fastcgi_param SERVER_NAME $server_name;
	fastcgi_param HTTPS $https;
	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_pass unix:/var/php-nginx/159566553311890.sock/socket;
	}
	listen 192.168.122.145:443 default ssl;
	ssl_certificate /home/debug-centos8-pro/ssl.cert;
	ssl_certificate_key /home/debug-centos8-pro/ssl.key;
	listen [fe80::b7de:f274:c493:9807];
}
~~~

Nginx appears to be even more fancy than Apache.

**Comment by iliarostovtsev** [comment]
I made a theme patch (irrelevant to this issue) but it shows what happens if you remove default IPv6.
https://github.com/authentic-theme/authentic-theme/commit/7776401ab94b136e8af94cc0ee98c89c91e79b87

**Comment by jcameron** [comment]
Maybe this is best a question for the Nginx folks, since it seems wrong that IPv6 has to be enabled globally before it can be enabled for a single IP.

**Comment by iliarostovtsev** [comment]
I wonder if this is still an issue?

I must run tests, I assume.

**Comment by willnode** [comment]
> I wonder if this is still an issue?

Actually I run into this problem. Everytime my customer spins up new server NGINX yells at me this error:

```
.. configuration is invalid : nginx: [emerg] a duplicate default server for [<ipv6>]:443 in /usr/local/conf/nginx.conf:735
nginx: configuration file /usr/local/conf/nginx.conf test failed
```

I notice you have made few changes about this. But i have no idea how to apply latest changes to my server.

**Comment by jcameron** [comment]
Ok, I see the bug that causes this - it can happen if a domain has an IPv6 address, but it's not private.

You can apply the code change in the patch linked above if you want an immediate fix.
