### ISSUE TITLE
php-fpm support

### ISSUE THREAD

**Issue by kintaro1981** [virtualmin/virtualmin-nginx#2]
Is it going to support php-fpm anytime soon?

please!!!

**Comment by swelljoe** [comment]
It's in the plans, but no fixed date for it. But, several big projects that were higher priority have been mostly wrapped up now, so we can probably start looking at it soon. I don't expect it to take terribly long (it looks a lot like the mod_fcgid configuration, and works very similarly), but we haven't done any work on it yet.

It's currently possible to set it up manually, and some folks in our forums have documented that process.

**Comment by jcameron** [comment]
Good news - implementation of FPM support is done! It will be included in the next Virtualmin release.
