### ISSUE TITLE
Changing default fastcgi_param values

### ISSUE THREAD

**Issue by stu177** [virtualmin/virtualmin-nginx#21]
Hi,

Is there any way to change the default `fastcgi_params` that are populated on virtual server creation in the nginx site configurations?

Because we use a deployment system using symlinks, everything uses `$realpath_root` rather than a set path or `$document_root`.

I've done a quick hack by just editing the block that generates it in `virtualmin-nginx-lib.pl` however I know this isn't a good or permanent solution.

Thanks

**Comment by jcameron** [comment]
Right now, no. However, I wonder if it would make sense to use `$realpath_root` instead of `$document_root` by default?

**Comment by stu177** [comment]
I can't see any drawback of using `$realpath_root` from doing a quick read up.

In their docs, nginx say:

> an absolute pathname corresponding to the root or alias directive’s value for the current request, with all symbolic links resolved to real paths

Should be fine as a default?

**Comment by jcameron** [comment]
Thanks - we'll change the default in future.
