### ISSUE TITLE
Can't access subserver log files for non-root users

### ISSUE THREAD

**Issue by willnode** [virtualmin/virtualmin-nginx#23]
My users can't access any of the sub-server Virtualmin Nginx logs. It simply says "You are not allowed to view this extra log".

I check the server log files list in `/syslog/`, this is what I get:

![image](https://user-images.githubusercontent.com/20214420/141265520-29e6e2ee-6fd9-45bc-bf6b-09713228a8aa.png)

I certainly sure that is not something we would expect. The number of repeating log files matches the sub-server count attached to this user.

I'm afraid a code patch alone won't fix the problem for the existing server.

**Comment by jcameron** [comment]
Can you attach a screenshot of the link the users are clicking on when they get that "You are not allowed" error message?

**Comment by jcameron** [comment]
Also, what does the file /etc/webmin/syslog/$USERNAME.acl contain (where $USERNAME is the domain owner's login)

**Comment by willnode** [comment]
OK, I attach raw screenshots here.

![image](https://user-images.githubusercontent.com/20214420/141377788-8375368c-d3cd-47b7-8d35-5a6799edb034.png)

![image](https://user-images.githubusercontent.com/20214420/141377860-c6753fda-9ecd-4467-900e-ee66113cae0c.png)

`cat /etc/webmin/syslog/maduradirectory.acl` returns:

```
syslog=0
extras=/var/log/virtualmin/diusapi.id_access_log	/var/log/virtualmin/diusapi.id_error_log	/var/log/virtualmin/diusapi.id_access_log	/var/log/virtualmin/diusapi.id_error_log	/var/log/virtualmin/diusapi.id_access_log	/var/log/virtualmin/diusapi.id_error_log	/var/log/virtualmin/diusapi.id_access_log	/var/log/virtualmin/diusapi.id_error_log	/var/log/virtualmin/diusapi.id_access_log	/var/log/virtualmin/diusapi.id_error_log	/var/log/virtualmin/diusapi.id_access_log	/var/log/virtualmin/diusapi.id_error_log	/var/log/virtualmin/diusapi.id_access_log	/var/log/virtualmin/diusapi.id_error_log	/var/log/virtualmin/diusapi.id_access_log	/var/log/virtualmin/diusapi.id_error_log
noedit=1
others=0
any=0
noconfig=1
```

Also:

```
webmin: 1.981
virtualmin: 6.17
virtualmin-nginx: 2.22-1
```

Note that this isn't just affecting one particular user. All my non-root users have this behavior.

**Comment by willnode** [comment]
Also,

+ `~/domains/<subdomainname>/logs` symlinks "seems" correct. (yes they point to correct subdomain name logs but these symlinks are not get updated when domain name was changed). `~/domains/tata-kelola-perpus.diusapi.id/logs` refers to `/var/log/virtualmin/tata-kelola-perpus.maduradirectory.com_error_log`.
+ NGINX records for access_log and error_log are correct.
+ My non-root users still can get the logs with SSH. e.g. `tail /var/log/virtualmin/tata-kelola-perpus.diusapi.id_error_log` works.

**Comment by willnode** [comment]
Could be this code be the cause of it?

https://github.com/virtualmin/virtualmin-nginx/blob/8365d310728a841f30cfbc7a1f768c2872047f61/virtual_feature.pl#L979-L982

it should be `$sd` instead of `$d`?

**Comment by jcameron** [comment]
Yes! Thanks for finding this ... I will fix this in the next release of the Nginx plugin.
