### ISSUE TITLE
php-loop.pl filled server memory

### ISSUE THREAD

**Issue by fabiomontefuscolo** [virtualmin/virtualmin-nginx#25]
Hello,

I totally lost the access for my machine, including SSH and virtualmin panel. A hard reboot brought it back to life and started to investigate the syslog.

Many processes invoked the oom-killer to free memory, and between the options of service to be killed, there were thousands of **php-loop.pl** running, and growing.

The relevant slice of log

```
Feb  4 21:15:21 popeye kernel: [13033.520872] miniserv.pl invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=0
Feb  4 21:15:21 popeye kernel: [13033.532523] miniserv.pl cpuset=/ mems_allowed=0
Feb  4 21:15:21 popeye kernel: [13033.533218] CPU: 1 PID: 1481 Comm: miniserv.pl Not tainted 4.19.0-18-amd64 #1 Debian 4.19.208-1
Feb  4 21:15:21 popeye kernel: [13033.555389] Mem-Info:
Feb  4 21:15:21 popeye kernel: [13035.579282] [  17029]  1000 17029     3144       35    61440      583             0 php-loop.pl
Feb  4 21:15:21 popeye kernel: [13035.580705] [  17032]  1000 17032     3144       35    61440      583             0 php-loop.pl
Feb  4 21:15:21 popeye kernel: [13035.582050] [  17105]  1000 17105     3144       35    61440      583             0 php-loop.pl
Feb  4 21:15:21 popeye kernel: [13035.583496] [  17127]  1000 17127     3144       34    61440      583             0 php-loop.pl
Feb  4 21:15:21 popeye kernel: [13035.585175] [  17129]  1000 17129     3144       34    61440      583             0 php-loop.pl
Feb  4 21:15:21 popeye kernel: [13035.586654] [  17131]  1000 17131     3144       35    61440      583             0 php-loop.pl
Feb  4 21:15:21 popeye kernel: [13035.588081] [  17134]  1000 17134     3144       35    61440      583             0 php-loop.pl
Feb  4 21:15:21 popeye kernel: [13035.589449] [  17135]  1000 17135     3144       35    61440      583             0 php-loop.pl
Feb  4 21:15:21 popeye kernel: [13035.590968] [  17136]  1000 17136     3144       35    61440      583             0 php-loop.pl
... repeating 2566 times
```

| Package | version |
|-------------|------------|
| webmin | 1.984 |
| webmin-virtualmin-nginx | 2.23 |
| webmin-virtualmin-nginx-ssl | 1.16 |

```
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
```

**Comment by jcameron** [comment]
Were these processes all running as different users?  Or did they all belong to a single domain's user?

**Comment by fabiomontefuscolo** [comment]
I am not sure. We had to hard reboot the machine. I found about the process in syslog, after rebooting.

But anyway, I suspect all the processes ran under the same user, because we have just 1 virtualserver in that machine.

**Comment by fabiomontefuscolo** [comment]
Uhmm, reading https://stackoverflow.com/questions/9199731/understanding-the-linux-oom-killers-logs, I understand all processes were running with uid = 1000.

**Comment by jcameron** [comment]
Can you post or attach the output  from the command `ps auxwwwww | grep php-loop` ?

**Comment by fabiomontefuscolo** [comment]
There is no output for that at current moment.

Well, the problem stopped happening after I purged php8.0-cgi (`dpkg --purge php8.0-cgi`).

`dpkg -l | grep php8.0-cgi` was prefixed as **rc** 

* r: the package was marked for removal
* c: the configuration files are currently present in the system

I am guessing the configuration files present in the system were messing with php-loop.pl. It seems php-loop.pl is used to wrap a script that detect the php version, based on the cgi config. Makes sense?

**Comment by jcameron** [comment]
I wonder if the real issue is that php-loop.pl was endlessly trying to run a PHP command that doesn't exist?

I will make a small code change to prevent this in future ..
