### ISSUE TITLE
Script installation fails on Webmin feature with Nginx

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-nginx#27]
Jamie, hi.

Using latest patches it doesn't seem possible to install a script. Here is the error and the stack:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4426533/162981461-d6e61380-c392-4e67-946f-ba4d1a6a5097.png">

Looks like a regression bug.

**Comment by jcameron** [comment]
Thanks .. I've just checked in a fix for this.

**Comment by iliajie** [comment]
That, works! Thank you.

**Comment by iliajie** [comment]
I'm afraid we have the same issue when enabling Webmin Login in Edit Virtual Server! 😞

**Comment by iliajie** [comment]
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/4426533/166241672-0eb4cecb-8ad2-45b1-b4dd-721dcaa068c2.png">

**Comment by iliajie** [comment]
Jamie, [this fix](https://github.com/virtualmin/virtualmin-nginx/commit/50bf966709ae387511f10e53eba31c64d8c666c4) works for me. Please have a look. It's not clear why `find_domain_server` receives a string instead of a dom hash ref?
