### ISSUE TITLE
New server config is created but configuration never applied

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-nginx#28]
Jamie, hello.

Using latest install on Rocky 8, it seems that Nginx configuration is never applied, and after initial default domain is created or after another domain is added, it only works after Nginx is restarted manually.

**Comment by jcameron** [comment]
Any idea why? Is this specific to Rocky 8, or does it also happen on CentOS 8?

**Comment by iliajie** [comment]
> Any idea why? Is this specific to Rocky 8

Yes, it seems we need a new `virtualmin-nginx/config` file, as current install calls `init.d` script to apply configuration and fails:

```

Failed to apply Nginx configuration : sh: /etc/init.d/nginx: No such file or directory
```

This must help. Is this [patch](https://github.com/virtualmin/virtualmin-nginx/commit/549b50b8bcdc4a4d00c7efdbec5fe085c1bdbf5d) correct?

**Comment by jcameron** [comment]
Yes, thanks for the patch!
