### ISSUE TITLE
Add option to proxy websockets

### ISSUE THREAD

**Issue by BluCobalt** [virtualmin/virtualmin-nginx#29]
Currently, Virtualmin will only proxy normal HTTP requests when you set up proxying through Server Configuration > Edit Proxy Website, which causes problems with web applications that rely on WebSockets to function. Right now, the only way to get WebSockets to work through an nginx proxy is to manually edit the location block and add a few lines in the configuration file, which is highly tedious to do from Virtualmin. I believe a good solution would be to add a checkbox to the Edit Proxy Website page that enables or disables proxying WebSockets. 

Right now, Virtualmin only configures the single proxy_pass directive, which works fine until you need to proxy a web app like uptime kuma:
```
location / {
	     proxy_pass         {proxy target};
}
```
However, if nginx is configured properly, it can also be used to proxy WebSockets:
```
location / {
	     proxy_pass        {proxy target};
             proxy_http_version 1.1;
             proxy_set_header   Upgrade $http_upgrade;
             proxy_set_header   Connection "Upgrade";
             proxy_set_header   Host $host;
}

**Comment by jcameron** [comment]
Thanks for letting us know about this. Are all those directives needed though, or just `proxy_http_version` ?

**Comment by BluCobalt** [comment]
It is my understanding that all the directives are needed.

**Comment by jcameron** [comment]
Hmmm ... In that case, is there any reason not to add those directives for all proxies?

**Comment by BluCobalt** [comment]
The only thing that comes to mind would be to reduce attack surface, by only proxying web sockets when explicitly enabled

**Comment by jcameron** [comment]
Ok .. I will add an optional feature to enable this in the Nginx module.

In the config, does "Upgrade" actually need to be in double quotes though?

**Comment by BluCobalt** [comment]
> In the config, does "Upgrade" actually need to be in double quotes though?

I just tried it, and it works without the quotes.

**Comment by jcameron** [comment]
Excellent! The next release of the Nginx plugin will add a config option to add these new directives for new proxies..

**Comment by BluCobalt** [comment]
Using wbm-virtualmin-nginx 2.27-1.noarch on RHEL 8.6, I'm not seeing an option to proxy websockets:
![image](https://user-images.githubusercontent.com/37788256/187022751-f6e1c9c1-98c5-4ce7-9835-205e4e012a43.png)
Is the option missing, or am I looking in the wrong place?

**Comment by iliajie** [comment]
That feature must be enabled on `Webmin / Servers ⇾ Nginx Webserver ⇾ Configuration: Configurable options` page.

**Comment by BluCobalt** [comment]
Found it! Thank you.
