### ISSUE TITLE
Missing `$->{'public_html_path'}` and `$d->{'public_html_dir'}`

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-nginx#30]
When using latest checked in code for Virtualmin Nginx plugin, after creating a domain these directives (`public_html_path` and `public_html_dir`) in domain config are not set.

This results into not working change/rename **Website documents sub-directory** on **virtual-server.name - Server Configuration ⇾ Website Options** page.

Perhaps, this also introduces other issues.

**Comment by jcameron** [comment]
Ok I checked in a fix that should resolve this.

**Comment by iliajie** [comment]
That works, thank you!

**Comment by jcameron** [comment]
Excellent! Can't believe I missed this before ..
