### ISSUE TITLE
Cannot Validate Virtual Servers

### ISSUE THREAD

**Issue by BluCobalt** [virtualmin/virtualmin-nginx#31]
Hello,
Trying to run `Limits and Validation > Validate Virtual Servers` causes virtualmin to throw the following error, and stop validation:
```
Failed to validate servers : virtualmin-nginx::feature_get_web_ssl_file failed : Can't use string ("ssl_certificate_key") as an ARRAY ref while "strict refs" in use at /usr/libexec/webmin/virtualmin-nginx/virtualmin-nginx-lib.pl line 210.
```
I was trying to diagnose a php error while installing roundcube through the install script, and tried validating the virtual server I was installing to.

**Comment by jcameron** [comment]
Looks like we have checked in a fix for this already, but it hasn't been released yet. The fix is here : https://github.com/virtualmin/virtualmin-nginx/commit/4adfeeeaa7f35949976326530f3a01839f2238a8

**Comment by BluCobalt** [comment]
Oh, I see. Do you know when the next release will be?

**Comment by jcameron** [comment]
Which version of the Nginx plugin are you on currently? You can see on the Features and Plugins page.

**Comment by BluCobalt** [comment]
"Nginx Website" is 2.23 and "Nginx SSL Website" is 1.17

**Comment by iliajie** [comment]
> Looks like we have checked in a fix for this already, but it hasn't been released yet. The fix is here : [4adfeee](https://github.com/virtualmin/virtualmin-nginx/commit/4adfeeeaa7f35949976326530f3a01839f2238a8)

Jamie, are we good to go with a new release?

**Comment by jcameron** [comment]
Sure we could do a new release ... can you just tag a new version?

**Comment by iliajie** [comment]
> Sure we could do a new release ... can you just tag a new version?

I will if you tell me that it's tested and ready to go?

**Comment by jcameron** [comment]
Yeah, I think it can go out.
