### ISSUE TITLE
FPM menu link is incorrect

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-nginx#32]
Hello, Jamie!

As we discussed earlier in PM (remember the latest screencast) FPM menu link is incorrect when used with Nginx.

I tried CentOS 7 (where default PHP 5 is used + additional PHP 7.4 and 8.0) and Rocky 8 (where default is PHP 7.2 + additional PHP 5.6, 7.4 and 8.1).

Every time you change PHP version the menu link always leads to default `/etc/php-fpm.d/00000000000.conf` disregard of PHP version selected.

Selected PHP version, when switched from PHP Options page work just fine.

**Comment by iliajie** [comment]
I have taken a closer look at it myself, found a bug, and fixed it https://github.com/virtualmin/virtualmin-nginx/commit/c7e6e8bddddd8408f4b450f7b0286d63ab2e72d2.

Jamie, although, there are plenty of other places (4x) in `virtual_feature.pl` file, where `virtual_server::get_php_fpm_config()` used without `$d` -- could you double check please if that's expected!?

**Comment by jcameron** [comment]
If `$d` is passed in, it will return the config for the domain's current version. Otherwise it will return the first available FPM config. So it depends on the context ..

**Comment by iliajie** [comment]
Alright!

After running multiple tests on multiple systems I can say that almost everything is perfect!

There is only small tiny issue is that when PHP highest version selected on the template in FPM mode doesn't work.

**Comment by iliajie** [comment]
@jcameron Jamie, have a look at this patch. It will fix it for both Apache and Nginx.

Fix to correctly pick highest available version in FPM mode - https://github.com/virtualmin/virtualmin-gpl/commit/7353ab4f720137712f39f8e62be1ef78ecd8c878
