### ISSUE TITLE
PHP: Logging is not enabled on creation time even if set to be enabled in templates

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-nginx#60]
When creating a new top-level virtual server using **Create Virtual Server** page and even though **Default PHP log file** is set to **Default (logs/php_log)** in templates, the `error_log` for PHP is never enabled on the creation time. Although, it can be manually enabled later using **Server Configuration ⇾ PHP Options** page, it should be enabled on virtual server creation time, according to the templates.

The issue happens for all PHP execution modes!

Also, it is worth mentioning that everything works just fine with Apache.

**Comment by jcameron** [comment]
Oh so this is only an issue when using Nginx?

**Comment by jcameron** [comment]
Oh I see the bug ... this will be fixed in the next release.

**Comment by iliajie** [comment]
Thanks! That fixes the problem.
