### ISSUE TITLE
PHP: Log rotation never added

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-nginx#61]
PHP log rotation record is never added even when PHP logging is manually enabled using **Server Configuration ⇾ PHP Options** page.

**Comment by jcameron** [comment]
Is this on a system that's been fully updated using the package manager?

**Comment by iliajie** [comment]
The fix from [that issue](https://github.com/virtualmin/virtualmin-nginx/issues/60) also fixes this log rotation as well.
