### ISSUE TITLE
Shared SSL certificate is not getting "broken"

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-nginx#63]
Hey Jamie!

If you remember in the past we fixed "breaking" shared SSL certificate in Apache if main main is deleted.

Nginx does _not_ do it right yet. If there is site A and site B, and site B is using SSL certificate of site A, when site A is deleted site B is still using certificate of site A, resulting in Nginx not being able to restart.

**Comment by jcameron** [comment]
Just checked in a fix that should resolve this!

**Comment by iliajie** [comment]
Thanks, it works as expected now!
