### ISSUE TITLE
Restore fails when SSL sharing is set to "Yes, even when owner is different"

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-nginx#64]
Hi Jamie! 

If I restore backed up domain on Nginx system (Alma) to another Nginx system (Debian) and SSL sharing is set to **"Yes, even when owner is different"**, then Virtualmin doesn't update SSL certificates paths in Nginx config. It results in Nginx not being able to restart. If I restore a backup taken on Apache system (Rocky) and restore to the same Nginx system (Debian), then restore happens correctly.

Also, if certificate sharing isn't set to **"Yes, even when owner is different"** then restore happens correctly even in Nginx system (Alma) to another Nginx system (Debian) case.

**Comment by jcameron** [comment]
Are the SSL cert paths different between the old and new systems? Like is one using ~/ssl and the other under /etc/ssl ?

**Comment by iliajie** [comment]
No, both use a new `/etc/` location.

**Comment by jcameron** [comment]
Which version of the Nginx SSL plugin are you testing with there?

**Comment by iliajie** [comment]
All recently checked in code from _master_.

**Comment by jcameron** [comment]
Ok the fix I just checked in should resolve this..

**Comment by iliajie** [comment]
The issue is resolved. Thanks!
