### ISSUE TITLE
problem on wordpress sub-links with nginx

### ISSUE THREAD

**Issue by danayen** [virtualmin/virtualmin-nginx#66]
When I install VM on ubuntu, everything looks good Also when I install wordpress (manual or script), it show first page correctly, but I cannot go to other pages like wp-admin, etc.
After many search and change a lot of things, I found that the nginx configuration file for website not defined a line!
So I want to add this line on nginx configuration, when we add new website on VM:
 `location /{ 
	    try_files $uri $uri/ /index.php?$args;
	}
`
It will add on websites nginx configuration file.

Also pls change upload file size on nginx main config file. I think that 32 MB is enough.

**Comment by jcameron** [comment]
Is this strictly necessary for wordpress to work under nginx? Or is it only needed if there's a wordpress option enabled to use short URLs or something?

**Comment by danayen** [comment]
I think it is necessary for wordpress. Without it the wordpress website not work (except main page) correctly.
I didn't test it on other platforms like laravel, prestashop, etc.

**Comment by jcameron** [comment]
@iliajie you test with Nginx a lot - have you run into this problem?

**Comment by iliajie** [comment]
@danayen If you go to your WordPress admin panel, in particular to **Settings ⇾ Permalinks**, what do you have set for **Permalink structure** option?

By default permalinks structure is set to **Plain** links, and everything works just fine. However, if you change it, you would also need to adjust Nginx configuration.

For example, if WordPress is installed under `/wordpress` then Nginx config should get the following to work correctly with permalinks:

```
location /wordpress/ {
        	try_files $uri $uri/ /wordpress/index.php?$args;
     	}
```

That would be fine to automatie this, I think. But we would also have to delete it on script uninstall. I'm not sure if it's worth the hassle. Probably is!

**Comment by danayen** [comment]
@iliajie As you know, at the most time we do not use  **Plain links** (due SEO reasons, we use **Post name** or **Custom Structure**). However, sometimes **Plain** not work correctly and maybe we have nginx error.
On the other hand, I build a new subdomain and installed under /wordpress by script, then I checked nginx config file. There is **_no line_** as:
```
location /wordpress/ {
        	try_files $uri $uri/ /wordpress/index.php?$args;
     	}

```
Built lines are:
```
location ^~ /.well-known/ {
		try_files $uri /;
	}
location ~ "\.php(/|$)" {
		try_files $uri $fastcgi_script_name =404;
                ...

location /cgi-bin/ {
		gzip off;
               ...
```
Again, when I changed **Plain** to **Post Name**, I had 404 error. 
Please note that we install wordpress in main root (public html, not /wordpress).

Maybe my Virtualmin is not installed in good way :) . 
So, pls don't be lazy :D . (I don't know where is it to change, we need just to adding a line to solve it).

I use mostly proxy version and work correcly, but I have a few wordpress websites and I want to migrate from cpanel to VM (I thing VM is better than cpanel).

**Comment by iliajie** [comment]
>  then I checked nginx config file. There is no line as .. Again, when I changed **Plain** to **Post Name**, I had 404 error.

This is expected (currently), as we don't change Nginx config after WordPress installation.

> I don't know where is it to change, we need just to adding a line to solve it.

I don't understand - you provided Nginx config examples, so you definitely should know how to change it and make it work.

**Comment by danayen** [comment]
> I don't understand - you provided Nginx config examples, so you definitely should know how to change it and make it work.
I mean on VM source code. But I can change manually.

> This is expected (currently), as we don't change Nginx config after WordPress installation.
Yes, so we need to change (only on Wordpress or generally).

**Comment by iliajie** [comment]
Next WordPress install script release will automate the process of adding and removing those Nginx `location` records.

Implemented on this PR:

https://github.com/virtualmin/virtualmin-gpl/pull/745
