### ISSUE TITLE
Nginx redirect module is not displaying consistently

### ISSUE THREAD

**Issue by pixel-paul** [virtualmin/virtualmin-nginx#68]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Rocky Linux 9.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |     All installed packages are up to date   |
| wbm-virtualmin-nginx | 2.32-1 |

If I create a redirect as below:

![image](https://github.com/virtualmin/virtualmin-nginx/assets/389303/1a1be402-8028-424d-8c53-8bd3f1293105)

I can see that Virtualmin has added this to the nginx conf:

`rewrite ^\Q/\E(.*) https://www.example.co.uk/ permanent;`

When I edit this, by clicking the `/` here:

![image](https://github.com/virtualmin/virtualmin-nginx/assets/389303/12acc89c-920b-4444-ba2c-8883061fddf3)

a different field is selected and populated than above:

![image](https://github.com/virtualmin/virtualmin-nginx/assets/389303/cf12b030-bfc2-4e43-aa08-382efd3a3e74)

This appears to be incorrect.

**Comment by iliajie** [comment]
Hello,

If you update `virtual_feature.pl` and `virtualmin-nginx-lib.pl` from [Nginx repo](https://github.com/virtualmin/virtualmin-nginx), restart Webmin, do you still get the same issue?

**Comment by pixel-paul** [comment]
The latest update has resolved this.

**Comment by iliajie** [comment]
It's good to know! Thanks for the feedback!
