### ISSUE TITLE
virtual_feature.pl crash when PHP not installed

### ISSUE THREAD

**Issue by esb** [virtualmin/virtualmin-nginx#7]
Not everyone wants or needs PHP on a server, but the virtual_feature.pl script crashes if it's not found.

The function feature_get_web_php_mode tries to determine the current PHP mode, but returns undef at line 1123 if it's not found. Unfortunately, this cases the callers of this function to crash when they use the result in a test statement (such as at 1132, and others). The code crashes because the returned value is undef. It would probably be better to return something like "none", and then all the tests would work properly.

**Comment by jcameron** [comment]
Thanks .. this will be fixed in the next release of the Nginx plugin.
