### ISSUE TITLE
Virtualmin mail autoconfiguration script does not properly work with Nginx

### ISSUE THREAD

**Issue by neosonic2** [virtualmin/virtualmin-nginx#70]
I'm running Virtualmin Pro 7.9.0 and Nginx module version 2.32 on Ubuntu 22.04 LTS, and have enabled mail client autoconfiguration within Virtualmin. As a result, the appropriate rewrite rules were added by Virtualmin to each of my virtual hosts, and I've additionally added a "/cgi-bin" location block to my Nginx configuration that captures requests to autoconfig.cgi and handles them properly (see [this thread in the Virtualmin forums](https://forum.virtualmin.com/t/how-to-get-nginx-to-support-mail-autoconfigure-or-any-other-cgi-bin-scripts/113194/3) for details).

However, autoconfig.cgi always returns XML for Thunderbird and other clients even when my original request URI is /autodiscover/autodiscover.xml, which should return XML for Outlook. I believe this is because the CGI script uses the "SCRIPT_NAME" environment variable to determine which XML to return based on whether the URI contained "autodiscover.xml" ([line 89](https://github.com/virtualmin/virtualmin-gpl/blob/master/autoconfig.cgi)), but Nginx always sets SCRIPT_NAME to /cgi-bin/autoconfig.cgi and doesn't seem to care what the original URI was (before the HTTP 302 redirect to the CGI script).

Is there a way to work around this issue? None of the FastCGI parameters contain the original request URI unfortunately, so autoconfig.cgi always thinks every request should return Thunderbird client XML even when I'm using Curl with /autodiscover.xml, using Outlook, or using the [Microsoft Remote Connectivity Analyzer](https://testconnectivity.microsoft.com/tests/Ola/input) tool to test my setup.

**Comment by jcameron** [comment]
Ah, that is probably because we use redirects in Nginx from `/autodiscover/autodiscover.xml` to `autoconfig.cgi`

Actually we don't look at the SCRIPT_NAME to determine whether to return Thunderbird or Outlook format - instead we use the request method (GET or POST). However, a POST request to `autodiscover.xml` gets redirected to a GET to `autoconfig.cgi` :-( 

It's unclear how to easily fix the Nginx config to better handle this case...

**Comment by neosonic2** [comment]
Thank you for the clarification. Given your explanation, I'm wondering if there's a way to write the redirect directives in the Nginx virtual hosts in such a way that the HTTP method is not changed when a redirect occurs?

According to [this page](https://blog.codefarm.me/2021/09/24/http-redirect-3xx/), in cases of redirection, the HTTP method used to make the new request to fetch the page pointed to by the "Location" response header depends on the original method and of the kind of redirection: 303 (See Other) responses always lead to the use of a GET method, 307 (Temporary Redirect) and 308 (Permanent Redirect) don’t change the method used in the original request, and 301 (Moved Permanently) and 302 (Found) don’t change the method most of the time, though older user-agents may (so you basically don’t know). Could we thus change the HTTP status code returned on redirect so that either Nginx or the connecting client do not force a method change at redirection time?

**Comment by jcameron** [comment]
Looks like a 307 redirect is what we want according to https://stackoverflow.com/questions/30048791/nginx-preserve-post

I'll fix this in the next release of the Nginx plugin for Virtualmin.

**Comment by neosonic2** [comment]
I performed further testing before I saw your email closing the issue, and managed to fix the problem by making an adjustment to Nginx and an adjustment to _autoconfig.cgi_. I'm not sure if the update you said you would include in the next module version release includes the same fixes, but wanted to note how I got things to work just in case you'd like to officially implement my solution.

First, I used Curl to make a POST request to the _/autodiscover/autodiscover.xml_ endpoint of my domain with the regular rewrite rules still configured in Nginx (so that an **HTTP 302 status code** was returned). The body of the request included the following XML to simulate a connection coming from Outlook (actual email address redacted):

```
<?xml version="1.0" encoding="utf-8"?>
<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/mobilesync/requestschema/2006">
    <Request>
        <EMailAddress>user@domain.com</EMailAddress>
        <AcceptableResponseSchema>http://schemas.microsoft.com/exchange/autodiscover/mobilesync/responseschema/2006</AcceptableResponseSchema>
    </Request>
</Autodiscover>
```

After being redirected I received the error, "EMailAddress missing from input XML". This told me that _autoconfig.cgi_ could see I was coming from Outlook, but the POST body was not being sent when Curl followed the HTTP 302 redirect. I thought Curl had made the request to _autoconfig.cgi_ using GET, but the script only returns the aforementioned error message when a POST request is made.

Then, I tested to see whether an **HTTP 307 redirect** would indeed preserve the POST body as theorized by adding the following to my Nginx virtual host configuration in place of the _/autodiscover/autodiscover.xml_ rewrite lines Virtualmin adds:

```
if ($uri ~* "^/(AutoDiscover|autodiscover)/AutoDiscover.xml(.*)") {
    return 307 $scheme://$host/cgi-bin/autoconfig.cgi;
}
```

When tested via Curl, this new configuration sent the POST body along with the request to _autoconfig.cgi_ rather than removing it at the point of redirection, thus getting rid of the error message, but still ended up ultimately returning XML for Thunderbird and not Outlook.

I discovered this was because [line 89](https://github.com/virtualmin/virtualmin-gpl/blob/master/autoconfig.cgi) of _autoconfig.cgi_, as mentioned in my original comment on this issue, does indeed look at the **SCRIPT_NAME** environment variable to determine whether to return XML for Outlook or Thunderbird, even if it already knew earlier in the process that Outlook was being used because of the check for the autodiscover XML in the POST body. Updating this line to check whether the **REQUEST_METHOD** parameter is set to POST resolved this problem and, after another test with Curl, I saw that XML for Outlook was finally returned as expected.

However, in another twist, both Outlook and the Microsoft Remote Connectivity Analyzer failed to pick up the autodiscover XML because neither recognized the HTTP 307 status code as a sign they needed to follow the redirect, and so they gave up at that point. It was then that I realized I needed to find a way to preserve the POST method and body on redirection without using the 307 status code, a "best of both worlds" scenario. I achieved this by replacing the **break** keyword with the **permanent** keyword in Virtualmin's original _autodiscover.xml_ rewrite statements. This causes an **HTTP 301 status code** to be returned, and Outlook and the Remote Connectivity Analyzer follow the redirect properly and successfully retrieve the XML they need.

Please let me know if you need any additional clarification as I realize this was a rather long explanation.

**Comment by jcameron** [comment]
Thanks for the detailed analysis and solution! We will update autoconfig.cgi to not look at SCRIPT_NAME and instead just use the request method.

Can you share the final Nginx config that worked for you?

**Comment by neosonic2** [comment]
Sure. I won't share the entire virtual host configuration since the only thing I needed to modify there were the rewrite rules Virtualmin put in place. The existing ones for Thunderbird were not touched, but the Outlook rules were updated so that the `break` keyword was replaced with `permanent`, like this:

```
rewrite ^\Q/AutoDiscover/AutoDiscover.xml\E(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 permanent;
rewrite ^\Q/Autodiscover/Autodiscover.xml\E(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 permanent;
rewrite ^\Q/autodiscover/autodiscover.xml\E(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 permanent;
```

Additionally, because Virtualmin doesn't add any configuration to Nginx to support handling CGI scripts, I had to add some of my own in a separate file that gets included in all virtual hosts via a post-processing script I created. That config looks like this:

```
location /cgi-bin/ {
    gzip off;
    autoindex on;
    fastcgi_pass unix:/var/run/fcgiwrap.socket;
    fastcgi_param SCRIPT_FILENAME $document_root/../$fastcgi_script_name;
    include /etc/nginx/fastcgi_params ;
}
```

This also required the installation of the `fcgiwrap` package in Ubuntu but that was easy enough.

**Comment by neosonic2** [comment]
For _autoconfig.cgi_, I updated line 89 to be the following:

```
if ($ENV{'REQUEST_METHOD'} eq 'POST') {
```

This worked even when checking for SCRIPT_NAME did not.
