### ISSUE TITLE
Upgrading from 2.32 to 2.35: Nginx website failed!

### ISSUE THREAD

**Issue by willnode** [virtualmin/virtualmin-nginx#71]
Here are full logs:

```
.. Nginx website failed! : virtualmin-nginx::feature_setup failed : virtualmin-nginx::feature_add_web_webmail_redirect failed : flush_file_lines called on non-loaded file /etc/nginx/conf.d//yellow-possession-lun.domcloud.dev.conf ../web-lib-funcs.pl (line 3882)
 ../web-lib-funcs.pl (line 4223)
 ../web-lib-funcs.pl (line 4223)
```

The error log shows up after upgrading from `wbm-virtualmin-nginx` from 2.32 to 2.35. Notetheless the website still created succesfully.

OS: Rocky Linux 9.4
Webmin: 2.111
Virtualmin: 7.0-1

**Comment by jcameron** [comment]
We're about to release a 2.36 version of the Nginx plugin that will fix this issue..

**Comment by willnode** [comment]
Will keep an eye for that. Thank you!

**Comment by willnode** [comment]
Just upgraded to 2.36. Thank you!
