### ISSUE TITLE
Include directives should not be resolved at site creation time

### ISSUE THREAD

**Issue by SpiffyStores** [virtualmin/virtualmin-nginx#8]
The function read_config_file in virtualmin-nginx-lib.pl currently parses the Nginx configuration files that are passed through the extra_dirs parameter from the server configuration templates.

The problem is that this function attempts to recursively process any include directives in the configuration and resolve them when the site files are being created. This defeats the purpose of the include directive which is meant to be resolved when Nginx is loaded, allowing you to update and modify parameters on a global basis, without having to go and edit each site configuration each time you want to change a parameter.

I'd like to suggest that the lines 128 - 139 in virtualmin-nginx-lib.pl be deleted to leave the include directive "as is" in the configuration file and allow Nginx to process it rather than having Virtualmin pre-process it when creating sites.

**Comment by SpiffyStores** [comment]
Actually the 'else' block would also need to be promoted out of the 'if' that is being deleted.

**Comment by jcameron** [comment]
Good point ... we'll fix this in the next release of the Nginx plugin.
